src/Entity/Application.php
<?php

namespace App\Entity;
use Cocur\Slugify\Slugify;
use App\Repository\ApplicationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
/**
 * @ORM\Entity(repositoryClass=ApplicationRepository::class)
 * @UniqueEntity(fields={"nom"}, message="Il existe déjà une application avec ce nom")
 * @ApiResource(
 *     collectionOperations={"post"},
 *     itemOperations={"get"}
 * )
 */
class Application
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Amelioration::class, mappedBy="application", orphanRemoval=true, cascade={"persist"}))
     */
    private $ameliorations;

    /**
     * @ORM\OneToMany(targetEntity=ApplicationImage::class, mappedBy="application", orphanRemoval=true, cascade={"persist"} )
     */
    private $images;

    /**
     * @ORM\OneToMany(targetEntity=ApplicationFichier::class, mappedBy="application", orphanRemoval=true)
     */
    private $fichiers;

    /**
     * @ORM\Column(type="integer")
     */
    private $nombre_telechargement;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $version;

    /**
     * @ORM\OneToMany(targetEntity=ApplicationTelechargementUser::class, mappedBy="application", orphanRemoval=true)
     */
    private $telechargement_user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $logo;

    /**
     * @ORM\Column(type="text")
     */
    private $description;


    public function __construct()
    {
        $this->ameliorations = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->fichiers = new ArrayCollection();
        $this->telechargement_user = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * @return Collection<int, Amelioration>
     */
    public function getAmeliorations(): Collection
    {
        return $this->ameliorations;
    }

    public function addAmelioration(Amelioration $amelioration): self
    {
        if (!$this->ameliorations->contains($amelioration)) {
            $this->ameliorations[] = $amelioration;
            $amelioration->setApplication($this);
        }

        return $this;
    }

    public function removeAmelioration(Amelioration $amelioration): self
    {
        if ($this->ameliorations->removeElement($amelioration)) {
            // set the owning side to null (unless already changed)
            if ($amelioration->getApplication() === $this) {
                $amelioration->setApplication(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ApplicationImage>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(ApplicationImage $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setApplication($this);
        }

        return $this;
    }

    public function removeImage(ApplicationImage $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getApplication() === $this) {
                $image->setApplication(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, ApplicationFichier>
     */
    public function getFichiers(): Collection
    {
        return $this->fichiers;
    }

    public function addFichier(ApplicationFichier $fichier): self
    {
        if (!$this->fichiers->contains($fichier)) {
            $this->fichiers[] = $fichier;
            $fichier->setApplication($this);
        }

        return $this;
    }

    public function removeFichier(ApplicationFichier $fichier): self
    {
        if ($this->fichiers->removeElement($fichier)) {
            // set the owning side to null (unless already changed)
            if ($fichier->getApplication() === $this) {
                $fichier->setApplication(null);
            }
        }

        return $this;
    }

    public function getNombreTelechargement(): ?int
    {
        return $this->nombre_telechargement;
    }

    public function setNombreTelechargement(int $nombre_telechargement): self
    {
        $this->nombre_telechargement = $nombre_telechargement;

        return $this;
    }

    public function getVersion(): ?string
    {
        return $this->version;
    }

    public function setVersion(string $version): self
    {
        $this->version = $version;

        return $this;
    }

    public function getSlug(): ?string
    {
        return (new Slugify())->slugify($this->slug);
    }

    public function setSlug(string $slug): self
    {
        $this->slug = (new Slugify())->slugify($slug);

        return $this;
    }

    /**
     * @return Collection<int, ApplicationTelechargementUser>
     */
    public function getTelechargementUser(): Collection
    {
        return $this->telechargement_user;
    }

    public function addTelechargementUser(ApplicationTelechargementUser $telechargementUser): self
    {
        if (!$this->telechargement_user->contains($telechargementUser)) {
            $this->telechargement_user[] = $telechargementUser;
            $telechargementUser->setApplication($this);
        }

        return $this;
    }

    public function removeTelechargementUser(ApplicationTelechargementUser $telechargementUser): self
    {
        if ($this->telechargement_user->removeElement($telechargementUser)) {
            // set the owning side to null (unless already changed)
            if ($telechargementUser->getApplication() === $this) {
                $telechargementUser->setApplication(null);
            }
        }

        return $this;
    }

    public function getLogo(): ?string
    {
        return $this->logo;
    }

    public function setLogo(string $logo): self
    {
        $this->logo = $logo;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }
}

src/Controller/Admin/ApplicationController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Application;
use App\Entity\ApplicationImage;
use App\Form\ApplicationLogoType;
use App\Form\ApplicationType;
use App\Repository\ApplicationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/my-account/application')]
class ApplicationController extends AbstractController
{
    private $parent_page = 'Application';
    #[Route('/', name: 'app_admin_application_index', methods: ['GET'])]
    public function index(ApplicationRepository $applicationRepository): Response
    {
        return $this->render('admin/application/index.html.twig', [
            'applications' => $applicationRepository->findAll(),
            'parent_page' => $this->parent_page
        ]);
    }

    #[Route('/new', name: 'app_admin_application_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ApplicationRepository $applicationRepository): Response
    {
        $application = new Application();
        $application->setNombreTelechargement(0);
        $form = $this->createForm(ApplicationType::class, $application);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $application->setSlug($application->getNom());

            //on recupere les images transmise
            $logo = $form->get('logo')->getData();
            if ($logo) {
                $fichier = md5(uniqid()) . '.' . $logo->getClientOriginalExtension();
                //on copie le fichier dans le dosiier uploads
                $logo->move(
                    $this->getParameter('application_images_directory'),
                    $fichier
                );
                //on stocke l'image dans la base de donnees 
                $application->setLogo($fichier);
            }

            //on recupere les images transmise
            $images = $form->get('images')->getData();
            foreach ($images as $image) {
                //om gener un nouveau nom de fichier
                $fichier = md5(uniqid()) . '.' . $image->getClientOriginalExtension();
                //on copie le fichier dans le dosiier uploads
                $image->move(
                    $this->getParameter('application_images_directory'),
                    $fichier
                );
                //on stocke l'image dans la base de donnees 
                $img = new ApplicationImage();
                $img->setNom($fichier);
                $application->addImage($img);
            }
            $applicationRepository->add($application);
            $this->addFlash('success', 'L\'application a été créé avec succès.');
            return $this->redirectToRoute('app_admin_application_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin/application/new.html.twig', [
            'application' => $application,
            'form' => $form,
            'parent_page' => $this->parent_page
        ]);
    }

    #[Route('/{id}', name: 'app_admin_application_show', methods: ['GET'])]
    public function show(Application $application): Response
    {
        return $this->render('admin/application/show.html.twig', [
            'application' => $application,
            'parent_page' => $this->parent_page
        ]);
    }

    #[Route('/{id}/edit', name: 'app_admin_application_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Application $application, ApplicationRepository $applicationRepository): Response
    {
        if(isset($_POST['delete']))
        {
            dd($_POST);
        }
        $form = $this->createForm(ApplicationType::class, $application);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $application->setSlug($application->getNom());
            //on recupere les images transmise
            $images = $form->get('images')->getData();
            foreach ($images as $image) {
                //om gener un nouveau nom de fichier
                $fichier = md5(uniqid()) . '.' . $image->getClientOriginalExtension();
                //on copie le fichier dans le dosiier uploads
                $image->move(
                    $this->getParameter('application_images_directory'),
                    $fichier
                );
                //on stocke l'image dans la base de donnees 
                $img = new ApplicationImage();
                $img->setNom($fichier);
                $application->addImage($img);
            }
            $this->addFlash('success', "L'application a été modifié avec succès");
            $applicationRepository->add($application);
            return $this->redirectToRoute('app_admin_application_index', [], Response::HTTP_SEE_OTHER);
        }

        //formulaire pour le logo
        $form2 = $this->createForm(ApplicationLogoType::class, $application);
        $form2->handleRequest($request);

        $ancien_logo = $application->getLogo();

        if ($form2->isSubmitted() && $form2->isValid()) {
            //on recupere les images transmise
            $logo = $form2->get('logo')->getData();
            // dd($logo);
            if ($logo) {
                $fichier = md5(uniqid()) . '.' . $logo->getClientOriginalExtension();
                //on copie le fichier dans le dosiier uploads
                $logo->move(
                    $this->getParameter('application_images_directory'),
                    $fichier
                );
                //on stocke l'image dans la base de donnees 
                $application->setLogo($fichier);
                //on supprimer l'ancienne image
                if(!empty($ancien_logo)){
                    $path = $this->getParameter('application_images_directory') . '/' . $ancien_logo;
                    if (file_exists($path)) {
                        unlink($path);
                    }
                }
            }
            // dd($application);
            $this->addFlash('success', "Le logo a été modifié avec succès");
            $applicationRepository->add($application);
            return $this->redirectToRoute('app_admin_application_index', [], Response::HTTP_SEE_OTHER);
        }
        return $this->renderForm('admin/application/edit.html.twig', [
            'application' => $application,
            'form' => $form,
            'form2' => $form2,
            'parent_page' => $this->parent_page
        ]);
    }

    #[Route('/{id}', name: 'app_admin_application_delete', methods: ['POST'])]
    public function delete(Request $request, Application $application, ApplicationRepository $applicationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete' . $application->getId(), $request->request->get('_token'))) {
            foreach ($application->getImages() as $key => $image) {
                $path = $this->getParameter('application_images_directory') . '/' . $image->getNom();
                if (file_exists($path)) {
                    unlink($path);
                }
            }

            foreach ($application->getFichiers() as $key => $applicationFichier) {
                $path = $this->getParameter('application_fichiers_directory') . '/' . $applicationFichier->getNom();
                if (file_exists($path)) {
                    unlink($path);
                }
            }
            $applicationRepository->remove($application);
            $this->addFlash('success', "L'application a été supprimé avec succès");
        }

        return $this->redirectToRoute('app_admin_application_index', [], Response::HTTP_SEE_OTHER);
    }

    

    /**
     * @Route("/delete/image/{id}", name="application_delete_image", methods={"DELETE"})
     */
    public function deleteImage(ApplicationImage $image, Request $request, EntityManagerInterface $entityManager)
    {
        //om verifi si le token est valide         
        if ($this->isCsrfTokenValid('delete' . $image->getId(), $request->request->get('_token'))) {
            $path = $this->getParameter('application_images_directory') . '/' . $image->getNom();
            if (file_exists($path)) {
                unlink($path);
            }
            $entityManager->remove($image);
            $entityManager->flush();
            return new JsonResponse(['success' => 1]);
        } else {
            return new JsonResponse(['error' => 'Token invalide'], 400);
        }
    }
}

src/Controller/Main/AboutController.php
<?php

namespace App\Controller\Main;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AboutController extends AbstractController
{
    /**
     * @Route("/about", name="about")
     */
    public function index(): Response
    {
        return $this->render('main/about/about.html.twig', []);
    }
}

src/Controller/Main/AppController.php
<?php

namespace App\Controller\Main;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AppController extends AbstractController
{
    /**
     * @Route("/app", name="main_app")
     */
    public function index(): Response
    {
        return $this->render('main/app/index.html.twig', [
            'controller_name' => 'AppController',
        ]);
    }
}

src/Controller/Main/CoursController.php
<?php

namespace App\Controller\Main;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CoursController extends AbstractController
{
    /**
     * @Route("/cours", name="cours")
     */
    public function index(): Response
    {
        return $this->render('main/cours/index.html.twig', [
            'controller_name' => 'CoursController',
        ]);
    }
    /**
     * @Route("/cours/initiation_a_l_algorithmique", name="cour_initiation_a_l_algorithmique")
     */
    public function show(): Response
    {
        return $this->render('main/cours/initiation_a_l_algorithmique.html.twig', [
            'controller_name' => 'CoursController',
        ]);
    }
}

templates/main/application/index.html.twig
{% extends 'main/base.html.twig' %}

{% block title %}Hello ApplicationController!{% endblock %}

{% block body %}
	<nav class="breadcrumb breadcrumb-1 border-none  py-1 bg-2 m-0">
		<a class="breadcrumb-item" href="/">{{"Home"|trans}}</a>
		<span class="breadcrumb-item text-white active">Formations</span>
	</nav>
	<!-- Application -->
	<section id="applications" class="bg-2">
		<div class="container pt-3">
			<div class="row">
				<div class="col-xl-12">				</div>
			</div>
		</div>
	</section>

{% endblock %}

templates/main/application/show.html.twig
{% extends 'main/base.html.twig' %}

{% block title %}
	{{ application.nom ~ ' '~ application.version}}
{% endblock %}

{% block favicon %}
	<link rel="shortcut icon" width="48px" height="48px" href="{{ asset( application.logo is null ? 'img/logo/logo-pmd-1.png': 'img/application/' ~ application.logo) }}" type="image/x-icon">
{% endblock %}

{% block javascripts %}{% endblock %}
{% block body %}
	<nav class="breadcrumb breadcrumb-1 border-none  py-1 bg-2 m-0">
		<a class="breadcrumb-item" href="/">{{"Home"|trans}}</a>
		<span class="breadcrumb-item text-white active">Applications</span>
	</nav>
	<!-- Application -->
	<section id="applications" class="bg-2">
		<div class="container pt-3">
			{% include "includes/_alerte.html.twig" %}
			<div class="row">
				<div class="col-xl-8 my-2">
					<p style="font-size:1.5rem; font-weight:bold">{{ application.nom }}
					</p>
				</div>
				<div class="col-xl-4 my-2">
					<div
						class="search">
						{# <p class="p-2">Rechercher dans notre site</p> #}
						{# <div class="input-group card-2">
							<input type="text" class="form-control" placeholder="Recherche">
							<button class="btn  btn-search bg-2">
								<i class="fas fa-search"></i>
							</button>
						</div> #}
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-xl-2">
					<div class="app-card bg-white">
						<img src="{{asset('img/application/' ~ application.logo )}}" alt="{{application.nom}}"/>
					</div>
				</div>
				<div class="col-xl-10">
					<div class="row">
						<div class="col-xl-12" style="min-height:200px">
							<div class="row pt-3">
								<div class="col-xl-2  border-right">
									<p>Vote</p>
									<i class="fa fa-star text-warning mr-1" aria-hidden="true"></i>
									4.1
								</div>
								<div class="col-xl-3 border-right">
									<p>Taille</p>
									<i class="fa fa-server text-primary mr-1" aria-hidden="true"></i>
									{{ file_size }}
								</div>
								<div class="col-xl-3 border-right">
									<p>Telechargemment</p>
									<i class="fa fa-download text-success mr-1" aria-hidden="true"></i>
									{{ application.nombreTelechargement}}
								</div>
								<div
									class="col-xl-4 pt-4">
									{# <a class="btn btn-4 my-1" href="#">
																												<i class="fa fa-envelope" aria-hidden="true"></i>
																												Contact du developpeur</a>
																											<a class="btn btn-4 my-1" href="#">
																												<i class="fa fa-home" aria-hidden="true"></i>
																												Voir dans Play Store</a> #}

									<a class="btn btn-4 my-1 btn-copy" data-copy="{{ url('app_main_application',{slug:application.slug}) }}" href="#">
										<i class="fa fa-copy" aria-hidden="true"></i>
										Copier le lien</a>
								</div>
							</div>
						</div>
					</div>

					{#% set application_telecharger = app.request.cookies.get('application_telecharger_' ~ application.id) %}
															{% if application_telecharger != ('application_telecharger_' ~ application.id) %}
																{% if fichier %}
																	<div class="row">
																		<p class="my-3">Pour acceder au telechargement , merci de renseigner votre nom et votre adresse email</p>
																		<div class="col-xl-6 mx-auto pt-3">
																			{{ form_start(form) }}
																			{{ form_widget(form) }}
																			<button type="sumbit" class="btn btn-2">
																				Acceder au Téléchargemment</button>
																			{{ form_end(form) }}
																		</div>
																	</div>
																{% endif %}
										
															{% else %}
																<div class="row">
																	<div class="col-xl-6 mx-auto pt-3">
										
																		<a href="{{path('download_application_fichier',{id:fichier.id})}}" class="btn btn-3">
																			<i class="fa fa-download text-danger"></i>
																			Télécharger</a>
																	</div>
																</div>
															{% endif %#}


				</div>
			</div>
			<div class="row">
				<div class="col-12">
					{{application.description|raw}}
				</div>
			</div>
			<div class="row mt-5">
				{% for key, item in application.images %}
					<div class="col-xl-2 p-2">
						<img class="img-fluid" src="{{ asset('img/application/' ~ item.nom ) }}" alt="application image">
					</div>
				{% endfor %}
			</div>
			<div class="row">
				<div class="col-xl-6 mx-auto pt-3">
					{% if fichier %}
						<a href="{{path('download_application_fichier',{id:fichier.id})}}" class="btn btn-3">
							<i class="fa fa-download text-danger"></i>
							Télécharger</a>
					{% endif %}
				</div>
			</div>
		</div>
	</section>

{% endblock %}